import java.util.HashMap;
public class locationdata {
    public static HashMap<Integer, String> getLocations() {
        HashMap<Integer, String> locations = new HashMap<>();
        locations.put(1, "LIM");
        locations.put(2, "Campus Cafe");
        locations.put(3, "Auditorium");
        locations.put(4, "LIT Engineering");
        locations.put(5, "LIT Pharmacy");
        locations.put(6, "LIT Architecture");
        locations.put(7, "LIT Pharmacy");
        locations.put(8, "Shri Baldev Raj Mittal Hospital");
        locations.put(9, "Girls Hostel 1");
        locations.put(10, "Girls Hostel 2");
        locations.put(11, "Girls Hostel 3");
        locations.put(12, "Girls Hostel 4");
        locations.put(13, "LIT Polytechnic");
        locations.put(14, "Business Block");
        locations.put(15, "Lovely Mall");
        locations.put(16, "Hotel Mgt");
        locations.put(17, "Mall - II");
        locations.put(18, "Education");
        locations.put(19, "Auditorium");
        locations.put(20, "LSB");
        locations.put(21, "Girl Hostel 5");
        locations.put(22, "Girl Hostel 6");
        locations.put(23, "Auditorium");
        locations.put(24, "Auditorium");
        locations.put(25, "Engineering");
        locations.put(26, "Engineering");
        locations.put(27, "Engineering");
        locations.put(28, "Engineering");
        locations.put(29, "Engineering");
        locations.put(30, "Chancellor Office");
        locations.put(31, "Administrative Block");
        locations.put(32, "Administrative Block");
        locations.put(33, "Engineering");
        locations.put(34, "Engineering");
        locations.put(35, "Engineering");
        locations.put(36, "Engineering");
        locations.put(37, "Engineering");
        locations.put(38, "Engineering");
        locations.put(39, "STP");
        locations.put(40, "Store");
        locations.put(41, "Staff Residence");
        locations.put(42, "Staff Residence");
        locations.put(43, "Boys Hostel 1");
        locations.put(44, "Boys Hostel 2");
        locations.put(45, "Boys Hostel 2");
        locations.put(46, "Boys Hostel 3");
        locations.put(47, "Boys Hostel 4");
        locations.put(51, "Boys Hostel 5");
        locations.put(52, "Boys Hostel 6");
        locations.put(53, "Academic Block 1");
        locations.put(54, "Academic Block 2");
        locations.put(55, "Academic Block 3");
        return locations;
    }
}
